# Generated by Django 5.2.12 on 2026-04-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
